namespace Companion.ViewModels.Wizard;

/// <summary>
/// One selectable player country. <see cref="Code"/> is the only persisted value; <see cref="Name"/>
/// and <see cref="FlagKey"/> are presentation metadata over the country flag PNGs shipped with the
/// app. Keeping the asset key out of the save lets the art layout change without replay drift.
/// </summary>
public sealed record CharacterCountryOption(string Code, string Name, string FlagKey);

/// <summary>
/// The complete offline country/territory flag set exposed by AMS2. Most codes are ISO 3166-1
/// alpha-3. England and Scotland use their established motorsport codes, and Kosovo uses the common
/// user-assigned XKX code. Flag keys are country-keyed so player nationality never depends on an AI
/// driver's identity. Existing saved three-letter codes remain stable.
/// </summary>
public static class CharacterCountryCatalog
{
    public static IReadOnlyList<CharacterCountryOption> Available { get; } =
    [
        Country("AFG", "Afghanistan", "afghanistan"),
        Country("ALB", "Albania", "albania"),
        Country("DZA", "Algeria", "algeria"),
        Country("AND", "Andorra", "andorra"),
        Country("AGO", "Angola", "angola"),
        Country("ATG", "Antigua and Barbuda", "antigua_and_barbuda"),
        Country("ARG", "Argentina", "argentina"),
        Country("ARM", "Armenia", "armenia"),
        Country("AUS", "Australia", "australia"),
        Country("AUT", "Austria", "austria"),
        Country("AZE", "Azerbaijan", "azerbaijan"),
        Country("BHS", "Bahamas", "bahamas"),
        Country("BHR", "Bahrain", "bahrain"),
        Country("BGD", "Bangladesh", "bangladesh"),
        Country("BRB", "Barbados", "barbados"),
        Country("BLR", "Belarus", "belarus"),
        Country("BEL", "Belgium", "belgium"),
        Country("BLZ", "Belize", "belize"),
        Country("BEN", "Benin", "benin"),
        Country("BTN", "Bhutan", "bhutan"),
        Country("BOL", "Bolivia", "bolivia"),
        Country("BIH", "Bosnia and Herzegovina", "bosnia_and_herzegovina"),
        Country("BWA", "Botswana", "botswana"),
        Country("BRA", "Brazil", "brazil"),
        Country("BRN", "Brunei", "brunei"),
        Country("BGR", "Bulgaria", "bulgaria"),
        Country("BFA", "Burkina Faso", "burkina_faso"),
        Country("BDI", "Burundi", "burundi"),
        Country("KHM", "Cambodia", "cambodia"),
        Country("CMR", "Cameroon", "cameroon"),
        Country("CAN", "Canada", "canada"),
        Country("CPV", "Cabo Verde", "cape_verde"),
        Country("CAF", "Central African Republic", "central_african_republic"),
        Country("TCD", "Chad", "chad"),
        Country("CHL", "Chile", "chile"),
        Country("CHN", "China", "china"),
        Country("COL", "Colombia", "colombia"),
        Country("COM", "Comoros", "comoros"),
        Country("CRI", "Costa Rica", "costa_rica"),
        Country("HRV", "Croatia", "croatia"),
        Country("CUB", "Cuba", "cuba"),
        Country("CYP", "Cyprus", "cyprus"),
        Country("CZE", "Czechia", "czech_republic"),
        Country("COD", "Democratic Republic of the Congo", "democratic_republic_of_the_congo"),
        Country("DNK", "Denmark", "denmark"),
        Country("DJI", "Djibouti", "djibouti"),
        Country("DMA", "Dominica", "dominica"),
        Country("DOM", "Dominican Republic", "dominican_republic"),
        Country("TLS", "Timor-Leste", "east_timor"),
        Country("ECU", "Ecuador", "ecuador"),
        Country("EGY", "Egypt", "egypt"),
        Country("SLV", "El Salvador", "el_salvador"),
        Country("ENG", "England", "england"),
        Country("GNQ", "Equatorial Guinea", "equatorial_guinea"),
        Country("ERI", "Eritrea", "eritrea"),
        Country("EST", "Estonia", "estonia"),
        Country("ETH", "Ethiopia", "ethiopia"),
        Country("FJI", "Fiji", "fiji"),
        Country("FIN", "Finland", "finland"),
        Country("FRA", "France", "france"),
        Country("GAB", "Gabon", "gabon"),
        Country("GMB", "Gambia", "gambia"),
        Country("GEO", "Georgia", "georgia"),
        Country("DEU", "Germany", "germany"),
        Country("GHA", "Ghana", "ghana"),
        Country("GRC", "Greece", "greece"),
        Country("GRD", "Grenada", "grenada"),
        Country("GTM", "Guatemala", "guatemala"),
        Country("GIN", "Guinea", "guinea"),
        Country("GNB", "Guinea-Bissau", "guinea-bissau"),
        Country("GUY", "Guyana", "guyana"),
        Country("HTI", "Haiti", "haiti"),
        Country("HND", "Honduras", "honduras"),
        Country("HKG", "Hong Kong", "hongkong"),
        Country("HUN", "Hungary", "hungary"),
        Country("ISL", "Iceland", "iceland"),
        Country("IND", "India", "india"),
        Country("IDN", "Indonesia", "indonesia"),
        Country("IRN", "Iran", "iran"),
        Country("IRQ", "Iraq", "iraq"),
        Country("IRL", "Ireland", "ireland"),
        Country("ISR", "Israel", "israel"),
        Country("ITA", "Italy", "italy"),
        Country("CIV", "Côte d'Ivoire", "ivory_coast"),
        Country("JAM", "Jamaica", "jamaica"),
        Country("JPN", "Japan", "japan"),
        Country("JOR", "Jordan", "jordan"),
        Country("KAZ", "Kazakhstan", "kazakhstan"),
        Country("KEN", "Kenya", "kenya"),
        Country("KIR", "Kiribati", "kiribati"),
        Country("XKX", "Kosovo", "kosovo"),
        Country("KWT", "Kuwait", "kuwait"),
        Country("KGZ", "Kyrgyzstan", "kyrgyzstan"),
        Country("LAO", "Laos", "laos"),
        Country("LVA", "Latvia", "latvia"),
        Country("LBN", "Lebanon", "lebanon"),
        Country("LSO", "Lesotho", "lesotho"),
        Country("LBR", "Liberia", "liberia"),
        Country("LBY", "Libya", "libya"),
        Country("LIE", "Liechtenstein", "liechtenstein"),
        Country("LTU", "Lithuania", "lithuania"),
        Country("LUX", "Luxembourg", "luxembourg"),
        Country("MKD", "North Macedonia", "macedonia"),
        Country("MDG", "Madagascar", "madagascar"),
        Country("MWI", "Malawi", "malawi"),
        Country("MYS", "Malaysia", "malaysia"),
        Country("MDV", "Maldives", "maldives"),
        Country("MLI", "Mali", "mali"),
        Country("MLT", "Malta", "malta"),
        Country("MHL", "Marshall Islands", "marshall_islands"),
        Country("MRT", "Mauritania", "mauritania"),
        Country("MUS", "Mauritius", "mauritius"),
        Country("MEX", "Mexico", "mexico"),
        Country("FSM", "Micronesia", "micronesia"),
        Country("MDA", "Moldova", "moldova"),
        Country("MCO", "Monaco", "monaco"),
        Country("MNG", "Mongolia", "mongolia"),
        Country("MNE", "Montenegro", "montenegro"),
        Country("MAR", "Morocco", "morocco"),
        Country("MOZ", "Mozambique", "mozambique"),
        Country("MMR", "Myanmar", "myanmar"),
        Country("NAM", "Namibia", "namibia"),
        Country("NRU", "Nauru", "nauru"),
        Country("NPL", "Nepal", "nepal"),
        Country("NLD", "Netherlands", "netherlands"),
        Country("NZL", "New Zealand", "newzealand"),
        Country("NIC", "Nicaragua", "nicaragua"),
        Country("NER", "Niger", "niger"),
        Country("NGA", "Nigeria", "nigeria"),
        Country("PRK", "North Korea", "north_korea"),
        Country("NOR", "Norway", "norway"),
        Country("OMN", "Oman", "oman"),
        Country("PAK", "Pakistan", "pakistan"),
        Country("PLW", "Palau", "palau"),
        Country("PSE", "Palestine", "palestine"),
        Country("PAN", "Panama", "panama"),
        Country("PNG", "Papua New Guinea", "papua_new_guinea"),
        Country("PRY", "Paraguay", "paraguay"),
        Country("PER", "Peru", "peru"),
        Country("PHL", "Philippines", "philippines"),
        Country("POL", "Poland", "poland"),
        Country("PRT", "Portugal", "portugal"),
        Country("QAT", "Qatar", "qatar"),
        Country("COG", "Republic of the Congo", "republic_of_the_congo"),
        Country("ROU", "Romania", "romania"),
        Country("RUS", "Russia", "russia"),
        Country("RWA", "Rwanda", "rwanda"),
        Country("KNA", "Saint Kitts and Nevis", "saint_kitts_and_nevis"),
        Country("LCA", "Saint Lucia", "saint_lucia"),
        Country("VCT", "Saint Vincent and the Grenadines", "saint_vincent_and_the_grenadines"),
        Country("WSM", "Samoa", "samoa"),
        Country("SMR", "San Marino", "san_marino"),
        Country("STP", "São Tomé and Príncipe", "sao_tome_and_principe"),
        Country("SAU", "Saudi Arabia", "saudi_arabia"),
        Country("SCO", "Scotland", "scotland"),
        Country("SEN", "Senegal", "senegal"),
        Country("SRB", "Serbia", "serbia"),
        Country("SYC", "Seychelles", "seychelles"),
        Country("SLE", "Sierra Leone", "sierra_leone"),
        Country("SGP", "Singapore", "singapore"),
        Country("SVK", "Slovakia", "slovakia"),
        Country("SVN", "Slovenia", "slovenia"),
        Country("SLB", "Solomon Islands", "solomon_islands"),
        Country("SOM", "Somalia", "somalia"),
        Country("ZAF", "South Africa", "south_africa"),
        Country("KOR", "South Korea", "south_korea"),
        Country("SSD", "South Sudan", "south_sudan"),
        Country("ESP", "Spain", "spain"),
        Country("LKA", "Sri Lanka", "sri_lanka"),
        Country("SDN", "Sudan", "sudan"),
        Country("SUR", "Suriname", "suriname"),
        Country("SWZ", "Eswatini", "swaziland"),
        Country("SWE", "Sweden", "sweden"),
        Country("CHE", "Switzerland", "switzerland"),
        Country("SYR", "Syria", "syria"),
        Country("TWN", "Taiwan", "taiwan"),
        Country("TJK", "Tajikistan", "tajikistan"),
        Country("TZA", "Tanzania", "tanzania"),
        Country("THA", "Thailand", "thailand"),
        Country("TGO", "Togo", "togo"),
        Country("TON", "Tonga", "tonga"),
        Country("TTO", "Trinidad and Tobago", "trinidad_and_tobago"),
        Country("TUN", "Tunisia", "tunisia"),
        Country("TUR", "Türkiye", "turkey"),
        Country("TKM", "Turkmenistan", "turkmenistan"),
        Country("TUV", "Tuvalu", "tuvalu"),
        Country("UGA", "Uganda", "uganda"),
        Country("UKR", "Ukraine", "ukraine"),
        Country("ARE", "United Arab Emirates", "united_arab_emirates"),
        Country("GBR", "United Kingdom", "united_kingdom"),
        Country("USA", "United States", "united_states"),
        Country("URY", "Uruguay", "uruguay"),
        Country("UZB", "Uzbekistan", "uzbekistan"),
        Country("VUT", "Vanuatu", "vanuatu"),
        Country("VAT", "Vatican City", "vatican_city"),
        Country("VEN", "Venezuela", "venezuela"),
        Country("VNM", "Vietnam", "vietnam"),
        Country("YEM", "Yemen", "yemen"),
        Country("ZMB", "Zambia", "zambia"),
        Country("ZWE", "Zimbabwe", "zimbabwe"),
    ];

    public static CharacterCountryOption? Find(string? code) =>
        string.IsNullOrWhiteSpace(code)
            ? null
            : Available.FirstOrDefault(option =>
                string.Equals(option.Code, code, StringComparison.Ordinal));

    private static CharacterCountryOption Country(string code, string name, string slug) =>
        new(code, name, $"country.{slug}");
}
