using Companion.Ams2.ContentLibrary;
using Companion.Ams2.CustomAi;
using Companion.Ams2.Preflight;
using Companion.Core.Grid;

namespace Companion.Ams2.Grid;

/// <summary>The outcome of staging one class XML into a CustomAIDrivers folder.</summary>
public sealed record StageResult
{
    /// <summary>Timestamped snapshot of whatever was at the target path before the write,
    /// or null when there was nothing to back up. NEVER null when a file was overwritten.</summary>
    public string? BackupPath { get; init; }

    public required string WrittenPath { get; init; }

    /// <summary>Human-readable summary (what was written, how many drivers, backup taken).</summary>
    public required string Report { get; init; }
}

/// <summary>
/// Turns a resolved <see cref="GridPlan"/> into an AMS2 custom-AI file and stages it. v1
/// regenerates the file before every round, so no per-track <c>tracks=</c> override entries
/// are emitted — the base entries already carry the round-final merged ratings.
/// </summary>
public static class GridStager
{
    /// <summary>Marker embedded in every generated file's header comment. Staging over a file
    /// WITHOUT this marker (the user's own community NAMeS file) requires force — a backup is
    /// taken either way, but clobbering curated files must be an explicit choice.</summary>
    public const string GeneratedMarker = "AMS2 Career Companion";

    // ---------- build ----------

    public static CustomAiFile Build(GridPlan plan, string? headerComment = null) => new()
    {
        VehicleClass = plan.Ams2Class,
        Drivers = plan.Seats.Select(ToCustomAiDriver).ToList(),
        HeaderComment = headerComment is { Length: > 0 }
            ? $" {GeneratedMarker} | {headerComment} "
            : $" {GeneratedMarker} ",
    };

    private static CustomAiDriver ToCustomAiDriver(GridSeat seat) => new()
    {
        LiveryName = seat.Ams2LiveryName,
        Name = seat.DriverName,
        Country = seat.Country,

        RaceSkill = seat.Ratings.RaceSkill,
        QualifyingSkill = seat.Ratings.QualifyingSkill,
        Aggression = seat.Ratings.Aggression,
        Defending = seat.Ratings.Defending,
        Stamina = seat.Ratings.Stamina,
        Consistency = seat.Ratings.Consistency,
        StartReactions = seat.Ratings.StartReactions,
        WetSkill = seat.Ratings.WetSkill,
        TyreManagement = seat.Ratings.TyreManagement,
        AvoidanceOfMistakes = seat.Ratings.AvoidanceOfMistakes,
        BlueFlagConceding = seat.Ratings.BlueFlagConceding,
        WeatherTyreChanges = seat.Ratings.WeatherTyreChanges,
        AvoidanceOfForcedMistakes = seat.Ratings.AvoidanceOfForcedMistakes,
        FuelManagement = seat.Ratings.FuelManagement,
        VehicleReliability = seat.Reliability,

        // Physics scalars are written only when they deviate from neutral: an entry-less field
        // means "stock car", and the scalars also affect the PLAYER when driving the livery.
        WeightScalar = ScalarOrNull(seat.WeightScalar),
        PowerScalar = ScalarOrNull(seat.PowerScalar),
        DragScalar = ScalarOrNull(seat.DragScalar),
    };

    private static double? ScalarOrNull(double scalar) => scalar == 1.0 ? null : scalar;

    // ---------- preflight ----------

    /// <summary>Delegates to <see cref="GridPreflight.Check"/>: class-name casing, livery
    /// bindings against installed overrides + stock names, grid size vs the venue's AI cap.</summary>
    public static PreflightReport Preflight(
        CustomAiFile file,
        Ams2ContentLibrary library,
        IReadOnlyCollection<InstalledLivery> installedLiveries,
        string? trackId = null,
        int? gridSize = null) =>
        GridPreflight.Check(file, library, installedLiveries, trackId, gridSize);

    // ---------- stage ----------

    /// <summary>
    /// Writes <c>&lt;VehicleClass&gt;.xml</c> into a CustomAIDrivers directory, ALWAYS
    /// snapshotting any existing file first via <see cref="CustomAiBackup.BackupIfPresent"/>
    /// (never overwrite without backup). When the existing file does not carry
    /// <see cref="GeneratedMarker"/> — i.e. it is the user's own file, not one we generated —
    /// the stage refuses unless <paramref name="force"/> is set.
    /// </summary>
    public static StageResult Stage(
        CustomAiFile file,
        string customAiDriversDirectory,
        DateTimeOffset now,
        bool force = false)
    {
        string target = Path.Combine(customAiDriversDirectory, file.VehicleClass + ".xml");

        if (!force && File.Exists(target) && !LooksGenerated(target))
        {
            throw new InvalidOperationException(
                $"'{target}' exists and was not generated by this app (community NAMeS file?). " +
                "Staging over it requires force — a timestamped backup is still taken first.");
        }

        // Backup FIRST, before any write touches the target.
        string? backupPath = new CustomAiBackup(customAiDriversDirectory)
            .BackupIfPresent(file.VehicleClass, now);

        CustomAiXmlWriter.WriteToDirectory(file, customAiDriversDirectory);

        string report =
            $"Staged {file.VehicleClass}.xml ({file.Drivers.Count} drivers) to '{target}'. " +
            (backupPath is null
                ? "No existing file — nothing to back up."
                : $"Previous file backed up to '{backupPath}'.");

        return new StageResult
        {
            BackupPath = backupPath,
            WrittenPath = target,
            Report = report,
        };
    }

    /// <summary>Scratch write with no backup and no force gate — for dry-run output folders
    /// only, NEVER a live CustomAIDrivers directory. Returns the written path.</summary>
    public static string DryRun(CustomAiFile file, string targetDirectory)
    {
        CustomAiXmlWriter.WriteToDirectory(file, targetDirectory);
        return Path.Combine(targetDirectory, file.VehicleClass + ".xml");
    }

    private static bool LooksGenerated(string path)
    {
        try
        {
            using var reader = new StreamReader(path);
            var buffer = new char[4096];
            int read = reader.ReadBlock(buffer, 0, buffer.Length);
            return new string(buffer, 0, read).Contains(GeneratedMarker, StringComparison.Ordinal);
        }
        catch (IOException)
        {
            return false;
        }
    }
}
