using Companion.Core.Numerics;
using Companion.Core.Scoring;

namespace Companion.Tests.Oracle;

/// <summary>
/// DTOs mirroring the f1db oracle fixture format (docs/dev/oracle-fixtures.md, v2).
/// One file per season at Fixtures/f1db/&lt;year&gt;.json, generated by tools/Companion.FixtureGen.
/// Deserialized with <c>Companion.Core.Json.CoreJson.Options</c> (camelCase properties,
/// camelCase string enums, <see cref="Rational"/> as "n"/"n/d" strings).
/// </summary>
public sealed record F1DbSeasonFixture
{
    public required int Year { get; init; }

    /// <summary>Races that season per f1db; feeds <c>ResolveScoringDefinition(roundCount)</c>.</summary>
    public required int RoundCount { get; init; }

    public required IReadOnlyList<F1DbRoundFixture> Rounds { get; init; }

    /// <summary>Official drivers standings from f1db <c>season_driver_standing</c>.</summary>
    public required IReadOnlyList<F1DbExpectedStanding> ExpectedDrivers { get; init; }

    /// <summary>Official constructors standings; omitted (null) for seasons before 1958.</summary>
    public IReadOnlyList<F1DbExpectedStanding>? ExpectedConstructors { get; init; }
}

public sealed record F1DbRoundFixture
{
    public required int Round { get; init; }

    /// <summary>f1db grand prix id, for traceability only, overrides are already resolved.</summary>
    public string? GrandPrixId { get; init; }

    /// <summary>"1/2" half points, "2" double points, "1" otherwise.</summary>
    public Rational PointsFactor { get; init; } = Rational.One;

    /// <summary>False for the Indianapolis 500, 1958–1960.</summary>
    public bool CountsForConstructors { get; init; } = true;

    /// <summary>2022+ shortened-race table key, when used.</summary>
    public string? AlternateRaceTableId { get; init; }

    public required IReadOnlyList<F1DbSessionFixture> Sessions { get; init; }
}

public sealed record F1DbSessionFixture
{
    /// <summary>"race" | "sprint", the fixture strings match the engine enum's camelCase form.</summary>
    public required SessionKind Kind { get; init; }

    /// <summary>ALL holders of the session's fastest time (ties: 1954 British GP had seven).</summary>
    public IReadOnlyList<string> FastestLapDriverIds { get; init; } = [];

    public required IReadOnlyList<F1DbEntryFixture> Entries { get; init; }
}

public sealed record F1DbEntryFixture
{
    public required string DriverId { get; init; }

    /// <summary>Chassis+engine championship key ("cooper+maserati"); null for entries outside
    /// the constructors championship (Indy 500 guest entrants).</summary>
    public string? ConstructorId { get; init; }

    /// <summary>Finishing position, 1-based; null when unclassified.</summary>
    public int? Position { get; init; }

    /// <summary>classified | retired | disqualified | notClassified | didNotStart | excluded —
    /// the fixture strings match the engine enum's camelCase form.</summary>
    public FinishStatus Status { get; init; } = FinishStatus.Classified;

    public bool SharedDrive { get; init; }

    /// <summary>False when the entry was classified but officially ineligible for championship
    /// points (F2 cars in the 1958/1967/1969 German GPs, unregistered second cars, annulled
    /// results). Derived by FixtureGen from f1db's per-row race_points, never authored.</summary>
    public bool PointsEligible { get; init; } = true;

    /// <summary>Position used for the points-table lookup when official scoring paid a
    /// different rank (1967/1969 German GPs: F1 cars paid by rank among eligible cars —
    /// Bonnier classified 6th, paid as 5th). Null: the classification position scores.</summary>
    public int? PointsPosition { get; init; }
}

/// <summary>One expected championship line, straight from f1db (points stored as REAL).</summary>
public sealed record F1DbExpectedStanding
{
    public required string Id { get; init; }

    /// <summary>Null when f1db has no position (e.g. the 1997 excluded Schumacher "EX" row).</summary>
    public int? Position { get; init; }

    public required double Points { get; init; }
}
