namespace Companion.ViewModels.Services;

/// <summary>
/// Additive season-end companion interface of the <see cref="ICareerSession"/> seam (like
/// <see cref="IForceStaging"/>): one-click restore of the user's pre-season AI file (locked
/// decision #7c). The current live file is ALWAYS re-backed-up first, restore never
/// destroys state. The season-review screen exposes this.
/// </summary>
public interface IAiFileRestore
{
    /// <summary>Re-backup the current class XML, then restore the pre-season original from
    /// the backup folder (the newest backup not generated by this app, falling back to the
    /// newest backup when every one is app-generated).</summary>
    RestoreOutcome RestoreOriginalAiFile();
}

public sealed record RestoreOutcome
{
    public required bool Success { get; init; }

    /// <summary>The backup file that was copied over the live class XML.</summary>
    public string? RestoredFromBackupPath { get; init; }

    /// <summary>Snapshot of the file that was live BEFORE the restore (taken first).</summary>
    public string? CurrentFileBackupPath { get; init; }

    public required IReadOnlyList<string> Messages { get; init; }
}
